### PR TITLE
Fix NullPointerException in git-stash-drop defaults

### PR DESCRIPTION
**Pull request by Nolan330**

### CODE REVIEW

**Comment by edannenberg** [comment]
Thanks for the PR! The test will need some improvement as untracked files are not stashed. Probably also a good idea to check we got a `RevCommit` after stashing.

**Comment by Nolan330** [comment]
Yeah, the test is flimsy. Was distracted in the moment. I’ll have a chance to add substance sometime later today. Thanks for your work on this library!

**Comment by Nolan330** [comment]
@edannenberg Running the tests locally fails with a `PGPException`:
```
Execution error (PGPException) at org.eclipse.jgit.lib.internal.BouncyCastleGpgKeyPassphrasePrompt/getPassphrase (BouncyCastleGpgKeyPassphrasePrompt.java:120).
missing credentials provider
```
Do you have any ideas around removing prerequisite environmental specification from the tests, or perhaps automating dummy credentials somehow? Would be happy to contribute in this area as well (so that future contributions needn't take so many cycles!).

**Comment by edannenberg** [comment]
Thanks for the update, merged and deployed to clojars as `1.0.0-beta3`.

> Running the tests locally fails with a PGPException

Can't reproduce this on my box. Do you have a password protected GPG key in your env?

**Comment by Nolan330** [comment]
@edannenberg really appreciate the response! I have a GPG key configured in the git cli to sign commits, but I would think that shouldn’t be necessary to run the tests. 

Do you think there would be a way to use something like `with-credentials` to spoof credentials for the tests? If there’s no way to mock the configuration to make the tests self-contained, it may be worth an addition to the README or a Wiki page documenting the environment requirements for contributors. If you agree, I’d be happy to look more into it and start a PR adding that documentation, since I’ll be going through it myself 😅

**Comment by edannenberg** [comment]
> Do you think there would be a way to use something like with-credentials to spoof credentials for the tests?

We could disable signing for the tests via `git config commit.gpgsign false`. Happy to accept a PR for this, let me know if you need any help.

**Comment by Nolan330** [comment]
I recently and abruptly realized that it’s the fact that I have a GPG key in my environment that triggers the `PGPException`. I apologize! I presumed `jgit` was unaware of my `git cli` config and the tests themselves were requiring GPG key configuration.

In that case, do you think it would be better to instead just make a note of this in the README, and have contributors manage their configuration manually? I think I’d prefer that myself, plus it’s less to manage.

If you agree, I’ll PR a brief addition to the README for contributors with commit signing configured.

Apologies again for misunderstanding what was going on with this.

**Comment by edannenberg** [comment]
No worries, my feedback wasn't exactly exhausting.

> In that case, do you think it would be better to instead just make a note of this in the README, and have contributors manage their configuration manually?

I think your use case is common enough to warrant automating it, I added some functions for reading/writing a repo's git config file. Should be fairly straight forward now to modify `with-tmp-repo` accordingly.

**Comment by Nolan330** [comment]
Thanks for the response @edannenberg. That looks great! I'll take a closer look at `with-tmp-repo` and open PR with the automated config changes sometime early next week.

Separately, I took a brief look at getting commit signing to actually work, but didn't find a way around that `PGPException`. The GPG key in the environment isn't password protected, so I'm not sure what's going wrong. Do you have any experience configuring commit signing through `jgit` on macOS? `commit` is the last action in my project that shells out rather than using the porcelain api because of this; it'd be great to be completely migrated.

Let me know if you have any ideas. I'll try debugging it directly in `jgit` as well, and see if their forums have any useful info. Thanks again for your help and work on this!

**Comment by edannenberg** [comment]
> Separately, I took a brief look at getting commit signing to actually work, but didn't find a way around that PGPException. The GPG key in the environment isn't password protected, so I'm not sure what's going wrong.

Prototyped a bit with signing today, turns out JGit currently does not support unprotected keys. See: [548763](https://bugs.eclipse.org/bugs/show_bug.cgi?id=548763). I added the missing support for password protected GPG keys to `git-commit`, you can also toggle signing directly via `:sign?` arg now.

**Comment by edannenberg** [comment]
@notalwaysgray fyi, unprotected gpg keys are supported now. see updated docs.

**Comment by notalwaysgray** [comment]
@edannenberg That's awesome. Coincidental timing as well—I'll be revisiting and improving the project that depends on `clj-jgit` near term, and will certainly love eliminating that last shell invocation. Thanks for letting me know!

**Pull request closed without merging**
