### PR TITLE
fix to run new lein in travis

### PR DESCRIPTION
**Pull request by jaromil**
trigger travis to see if this fixes the build

### CODE REVIEW

**Comment by edannenberg** [comment]
Sounds like the travis servicehook is not active in github settings. Maybe @dsabanin can shed some light on this?

**Comment by dsabanin** [comment]
I don't think the build was ever green for this project. Travis probably needs to be setup from scratch now.

**Comment by edannenberg** [comment]
@dsabanin It seems to be a general setup problem as Travis build doesn't trigger at all for a while now. See [history](https://travis-ci.org/clj-jgit/clj-jgit/builds). So either it got disabled at some point, or maybe things changed and require re-auth/setup. Could you check if the general [travis-setup](https://docs.travis-ci.com/user/getting-started/) is still ok?

**Comment by dsabanin** [comment]
You should be able to do that, as it looks like Travis is using GitHub admin/contributor status to authorize access to settings. Give it a try:

https://travis-ci.org/clj-jgit/clj-jgit/settings

I checked myself but I don't see any setting disabling automatic builds:

screen shot 2018-01-30 at 12 34 03 pm

**Comment by edannenberg** [comment]
I suspect it's something on the github side as the [requests](https://travis-ci.org/clj-jgit/clj-jgit/requests) tab doesn't show any push events that happened yesterday.

**Comment by edannenberg** [comment]
@dsabanin Just checked on one of my travis enabled github repos, `Settings > Integrations & Services` then edit the `Travis CI` hook. Maybe the hook got deactivated at some point to prevent spam, the page also has a `Test Service` button (top right) if the hook is already active.

**Comment by dsabanin** [comment]
@edannenberg I couldn't find any hook. You should be able to get into GitHub repo settings, I made you an admin (if you were not already, it was hard to tell).

**Comment by jaromil** [comment]
If this takes too much effort it may be worth to open a new build on circleci. Same service, mostly. I'll do that easily after this try. Sorry to raise a whole issue, but I really like to have a CI running tests on branches and PRs before merging...

**Comment by edannenberg** [comment]
@dsabanin Well that would explain things too. :) Confirming I can access the settings now, will take care of the rest. Thanks!

@jaromil I think we just need to setup the github travis hook again and things should work, but if CircleCI has any advantages this would probably a good point to start using it. Not too familiar with either other then running some tests on Travis. Also thanks for the PR, somehow totally missed there was a Travis setup.

**Comment by edannenberg** [comment]
Push events should be working again. As for getting the green lamp, looks like there is an issue with the [read-only-repo](https://github.com/clj-jgit/clj-jgit/blob/master/test/clj_jgit/test/helpers.clj#L10) macro and the Travis environment. Maybe `(System/getProperty "user.dir")`? Though an initial search suggests its fine. Probably best to add some temp. logging to see what's going on.

@jaromil Sorry for the drive-by commit btw, feel free to squash it with the rest.

**Comment by jaromil** [comment]
rebased and pushed, travis is triggered.

**Comment by edannenberg** [comment]
> Also locally I get errors, which are a bit confusing.

If it's the same errors as on Travis that would be nice. :P Tests work fine for me locally (and I would guess most people)

```
$ lein with-profile dev test
...
Ran 6 tests containing 29 assertions.
0 failures, 0 errors.
```

The Travis errors suggest that the test repo is not working as expected in that environment.

**Comment by edannenberg** [comment]
Hey @jaromil, did you get any further with this? Still curious what those errors are you are getting locally, is it the same issue as on travis?

**Comment by jaromil** [comment]
Still stuck on the same error and haven't found time to continue yet.
My next strategy will be to setup a OSX build which is also nicely provided by travis, i.e:
```yaml
os:
- linux
- osx
sudo: required
services:
  - docker
```
[...]
```yaml
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (build) ;fi
```

**Comment by edannenberg** [comment]
Had another look at the Travis log:

    git clone --depth=50 https://github.com/clj-jgit/clj-jgit.git clj-jgit/clj-jgit

Apparently Travis creates a `shallow` clone, but the tests use commit ids that don't exist in the truncated history. Workaround for `.travis.yml`:

```
git:
  depth: 9999999
```

What is the issue on osx?

**Comment by jaromil** [comment]
Great!!! well done!!! this was very important for me, I don't like to touch big things without tests on CI :^)
I can close this PR now. For running tests on OSX provided by Travis, if that is desired I can add them in another PR.

**Pull request closed without merging**
