### PR TITLE
Satisfy misc linting

### PR DESCRIPTION
**Pull request by vemv**
Satisfies the most important faults found by clj-kondo and Eastwood.

`lein test` kept passing on my machine :)

Cheers - V

### CODE REVIEW

**Comment by edannenberg** [comment]
Thanks for the PR and sorry for the delay, very limited time unfortunately this past month. I'll try to get it merged this week and also add some linting to the github actions run. Speaking of, why didn't it trigger for your PR? :thinking:

**Comment by octoshikari** [comment]
You need pull_request  into workflow file. After that action should be start after any PR created
```yaml
on: [push, pull_request]
```

**Comment by edannenberg** [comment]
Did GitHub change something? This worked before. Anyways I added it and also fixed the remaining linting issues.

@vemv i tried pushing to this branch but got a permission denied. maybe because I'm not the original maintainer? :thinking: Could you rebase this with current master as a test?

**Comment by octoshikari** [comment]
I think it related to how PR has been created. As example I've fork repo and create PR from my forked repository

**Comment by edannenberg** [comment]
Possibly, looks like the push event triggered on my non-fork branch PRs. If you rebase your PR it should hopefully trigger testing now.

**Comment by octoshikari** [comment]
For linting step in workflow you can add this options `--fail-level error --parallel`. Parallel will speed up lint process. Fail level will fail only for error in rules. Current warnings like unused value will not fail whole workflow

**Comment by edannenberg** [comment]
@vemv Thanks again for your contribution and apologies it took so long to get it merged. <3

**Pull request merged**
